### PR TITLE
remove contribution specific code

### PR DESCRIPTION
**Pull request by alexduf**
I'm not familiar with this project so please be extra careful when reviewing this PR.

I have removed everything that was making sense as being a direct dependency of the stripe web hook.

I have compiled and tested the branch but haven't tried to run the project as the setup is non trivial.

let me know if I missed anything

### CODE REVIEW

**Comment by paulbrown1982** [comment]
Looks good, however we've got a big change (to delete a load of subs stuff) which we'd like to go ahead of this which may cause conflicts with this checking, which we're happy to resolve.

**Comment by johnduffell** [comment]
is this still going anywhere or should be closed?

**Comment by paulbrown1982** [comment]
cc @alexduf ?

**Comment by alexduf** [comment]
I think this should be merged, contribution's webhook doesn't go through this service, so this is essentially dead code

**Comment by johnduffell** [comment]
this is winning the prize for oldest PR surely!  pretty heavily conflicted too.

**Comment by johnduffell** [comment]
looks pretty uncontroversial to me, I'm not sure anyone knows the code that well! 👍 but needs the conflicts sorting before it can go. Also @pvighi is shipping some changes in the near future so it may be worth coordinating

**Comment by johnduffell** [comment]
🔪

**Pull request closed without merging**
