### PR TITLE
Improve logging around card updates

### PR DESCRIPTION
**Pull request by jacobwinch**
### Why do we need this? 
I recently attempted to investigate problems related to card updates, and the lack of user-specific logging made this very difficult.

Making this process reliable is one way we can drive down our negative service contacts (and churn). It's very hard to make a process reliable if you can't work out when/why it's going wrong.

I know there are better/more comprehensive solutions that could be put in place, but this should make things better in the interim.

cc @johnduffell 

### The changes 
* Add logging for card update failure and success cases

### trello card/screenshot/json/related PRs etc
N/A

### CODE REVIEW

**Comment by johnduffell** [comment]
> drive down our negative service contacts

:1st_place_medal:

**Comment by johnduffell** [comment]
logging 📚 👍

**Comment by jacobwinch** [comment]
Can see card updates going through in PROD:
https://membership-logs.gutools.co.uk/app/kibana#/discover?_g=()&_a=(columns:!(_source),index:'logstash-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'message:%22Successfully%20updated%20card%22')),sort:!('@timestamp',desc))

**Comment by johnduffell** [comment]
nice! 🎉

**Pull request merged**
